### ISSUE TITLE
qa-list有bug要改

### ISSUE THREAD

**Issue by w1ndys** [W1ndys-bot/QASystem#2]
2024-08-28 11:41:51 INFO:root:处理消息: {'self_id': 3649056059, 'user_id': 2769731875, 'time': 1724816511, 'message_id': 916514256, 'message_seq': 916514256, 'real_id': 916514256, 'message_type': 'group', 'sender': {'user_id': 2769731875, 'nickname': '𝐖𝟏𝐧𝐝𝐲𝐬', 'card': '', 'role': 'owner'}, 'raw_message': 'qa-list', 'font': 14, 'sub_type': 'normal', 'message': [{'type': 'text', 'data': {'text': 'qa-list'}}], 'message_format': 'array', 'post_type': 'message', 'group_id': 728077087}
2024-08-28 11:41:51 INFO:root:处理群消息,群ID:728077087
2024-08-28 11:41:51 INFO:root:[API]已发送合并转发消息: []
2024-08-28 11:41:51 INFO:root:处理消息: {'status': 'failed', 'retcode': 1200, 'data': None, 'message': 'Error: 消息体无法解析, 请检查是否发送了不支持的消息类型\n    at OneBotMsgApi.sendMsgWithOb11UniqueId (file:///app/napcat/napcat.mjs:20491:13)\n    at GoCQHTTPSendForwardMsg._handle (file:///app/napcat/napcat.mjs:27885:56)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GoCQHTTPSendForwardMsg.websocketHandle (file:///app/napcat/napcat.mjs:27751:23)\n    at async OB11PassiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:13339:23)', 'wording': 'Error: 消息体无法解析, 请检查是否发送了不支持的消息类型\n    at OneBotMsgApi.sendMsgWithOb11UniqueId (file:///app/napcat/napcat.mjs:20491:13)\n    at GoCQHTTPSendForwardMsg._handle (file:///app/napcat/napcat.mjs:27885:56)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GoCQHTTPSendForwardMsg.websocketHandle (file:///app/napcat/napcat.mjs:27751:23)\n    at async OB11PassiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:13339:23)', 'echo': 'send_forward_msg'}

**Comment by w1ndys** [comment]
已修复
